---
 - name: create nginx site config
   template: src=nginx.conf dest=/etc/nginx/sites-available/{{app_name}}.conf
   notify:
    - restart nginx

 - name: link nginx config
   file: src=/etc/nginx/sites-available/{{app_name}}.conf dest=/etc/nginx/sites-enabled/{{app_name}}.conf state=link
